export const passActions = {
    SET_CUISINES: 'SET_CUISINES',
    SET_LOAD_CUISINES: 'SET_LOAD_CUISINES',
    SET_RESTAURANTS: 'SET_RESTAURANTS',
    SET_LOAD_RESTAURANTS: 'SET_LOAD_RESTAURANTS',
     SET_CURATEDLIST: 'SET_CURATEDLIST',
    SET_LOAD_CURATEDLIST: 'SET_LOAD_CURATEDLIST',
    SET_MENULIST: 'SET_MENULIST',
    SET_LOAD_MENULIST: 'SET_LOAD_MENULIST',
    SET_RESTAURANT: 'SET_RESTAURANT',
    SET_LOAD_RESTAURANT: 'SET_LOAD_RESTAURANT',
}
export const errorActions = {
    SET_ERROR: 'SET_ERROR',
    RESET_ERROR: 'RESET_ERROR'
}

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
